"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Company = { id: string; name: string };
type Drive = { id: string; title: string; status: string; companies: { name: string } | null };

export default function AdminDrivesPage() {
  const [companies, setCompanies] = useState<Company[]>([]);
  const [drives, setDrives] = useState<Drive[]>([]);
  const [companyId, setCompanyId] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [eligibility, setEligibility] = useState("");
  const [message, setMessage] = useState("Loading companies...");
  const [pending, setPending] = useState(false);
  useEffect(() => { Promise.all([fetch("/api/companies"), fetch("/api/drives?status=draft")]).then(async ([companiesResponse, drivesResponse]) => { const companiesResult = await companiesResponse.json(); const drivesResult = await drivesResponse.json(); if (!companiesResponse.ok) throw new Error(companiesResult.error?.message ?? "Unable to load companies."); if (!drivesResponse.ok) throw new Error(drivesResult.error?.message ?? "Unable to load drives."); setCompanies(companiesResult.data ?? []); setCompanyId(companiesResult.data?.[0]?.id ?? ""); setDrives(drivesResult.data?.items ?? []); setMessage(""); }).catch((error: Error) => setMessage(error.message)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); try { const response = await fetch("/api/drives", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ company_id: companyId, title, description, eligibility_criteria: eligibility }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Unable to create drive."); setDrives((current) => [result.data, ...current]); setTitle(""); setDescription(""); setEligibility(""); setMessage("Draft drive created. It is not visible to students until published."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create drive."); } finally { setPending(false); } }
  async function changeStatus(id: string, action: "publish" | "close") { const response = await fetch(`/api/drives/${id}/${action}`, { method: "POST" }); const result = await response.json(); if (!response.ok) { setMessage(result.error?.message ?? `Unable to ${action} drive.`); return; } setDrives((current) => current.map((drive) => drive.id === id ? { ...drive, status: result.data.status } : drive)); setMessage(action === "publish" ? "Drive published and notice created for every student." : "Drive closed."); }
  return <main className="portal-page"><header className="portal-header"><Link className="brand" href="/admin/dashboard"><span className="brand-mark">PP</span><span><strong>Placement Portal</strong><small>GBPUAT Pantnagar</small></span></Link><Link className="text-link" href="/admin/dashboard">Admin dashboard</Link></header><section className="admin-content"><p className="eyebrow">Drive builder</p><h1>Shape the next opportunity.</h1><form className="admin-form" onSubmit={submit}><label>Company<select required value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="">Select a company</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label>Role title<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Jr. Software Developer" /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={4} placeholder="Role details and process" /></label><label>Eligibility information<textarea value={eligibility} onChange={(event) => setEligibility(event.target.value)} rows={3} placeholder="Shown for student self-assessment only" /></label><button className="button button-accent" disabled={pending || !companyId} type="submit">{pending ? "Creating..." : "Create draft drive"} <span aria-hidden="true">-&gt;</span></button>{message && <p className="form-message" role="status">{message}</p>}</form><div className="admin-list"><h2>Draft drives</h2>{drives.length ? drives.map((drive) => <div className="admin-list-item" key={drive.id}><span><strong>{drive.companies?.name ?? "Company"}</strong> / {drive.title}</span><span className="admin-actions"><Link className="text-link" href={`/admin/drives/${drive.id}/applicants`}>Applicants</Link><button className="button button-accent" onClick={() => changeStatus(drive.id, "publish")}>Publish</button></span></div>) : <p className="dashboard-copy">No draft drives yet.</p>}</div></section></main>;
}